### ISSUE TITLE
client_credentials grant with RestOperation

### ISSUE THREAD

**Issue by bryantp** [spring-cloud/spring-cloud-security#109]
Hello All,

How would I configure an `OAuth2RestOperations` to make a client credentials call (With those credentials stored in the `application.yaml` to a remote OAuth2 auth server? Whenever I try to make the call as an anonymous user, I get the following error:

```
org.springframework.security.authentication.InsufficientAuthenticationException: Authentication is required to obtain an access token (anonymous not allowed)
```

As part of my flow, I cannot be authenticated as an actual user, but the client app should have the authority to make that call. Is there something wrong with the configuration?

```
security:
  oauth2:
    client:
      clientId: info-service
      clientSecret: secret
      authorizedGrantTypes: client_credentials
      scope: scim.write
      authorities: scim.write
```

Thanks for any help.
