### ISSUE TITLE
Declarative configuration of which routes require OAuth2 authentication

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-security#19]
E.g.

```
oauth2:
  proxy:
     routes:
        customers: true
```
