### ISSUE TITLE
Clarify use of user roles and (maybe also) basic auth for actuator endpoints

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-security#28]

**Comment by NickPadilla** [comment]
Hey @dsyer - This would be useful for me. I am attempting to use this configuration 
```
management:
  security:
    role: admin
    enabled: true
  context_path: /admin
```
In the hopes that I could get the endpoints to only allow users with an 'admin' role to view.  Having this documentation would be helpful.
