### ISSUE TITLE
should not "spring.oauth2.resource.id" be mapped to resourceId?

### ISSUE THREAD

**Issue by beku8** [spring-cloud/spring-cloud-security#53]
Should not the property ```spring.oauth2.resource.id``` be mapped automatically to ```resourceId``` without having to explicitly define the in the ```ResourceServerSecurityConfigurer```? 

```ResourceServerProperties``` class looks like it should
```
...
public String getResourceId() {
    return id;
}
```

**Comment by dsyer** [comment]
It is (https://github.com/spring-cloud/spring-cloud-security/blob/master/src/main/java/org/springframework/cloud/security/oauth2/resource/OAuth2ResourceConfiguration.java#L79).

**Comment by beku8** [comment]
Do I have to explicitly set this(```resources.resourceId(resource.getResourceId());```)? Otherwise doesn't seem to be working in my case:
```
spring:
  oauth2:
    resource:
      id: resource-name
      jwt:
        keyValue: ...
    client:
      clientId: ${spring.application.name}
```
