### ISSUE TITLE
Ribbon support to contact the auth server

### ISSUE THREAD

**Issue by masrawi** [spring-cloud/spring-cloud-security#61]
it would be great if I could replace `localhost:9999` with the name of the eureka service id
```
spring:
  application:
    name: ui-service
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
```

**Comment by dsyer** [comment]
I agree that might be cool, when the auth server is a registered service. Contributions gladly accepted. Note (for anyone attempting a pull request): the `userAuthorizationUri` is passed back to the browser ina redirect, so we would need to inject a custom `RedirectResolver`. The `accessTokenUri` is used in a back channel inside the `OAuth2RestTemplate`, so it will also be fiddly (but not impossible) to override the nested `RestTemplate` used for that call.

**Comment by huningd** [comment]
We have the same situation for property security.oauth2.resource.userInfoUri. In this case wouldn't it be enough to inject the DiscoveryClient into org.springframework.boot.autoconfigure.security.oauth2.resource.UserInfoTokenServices? If a DiscoveryClient is available we use it to resolve the userinfo service uri. Something like this:
```java
public UserInfoTokenServices(String userInfoEndpointUrl, String clientId, DiscoveryClient discoveryClient){
	String uri = discoveryClient.getInstances(userInfoEndpointUrl).get(0).getUri().toString();
	this.userInfoEndpointUrl = uri;
	this.clientId = clientId;
}
```
If that is enough I would enhance the UserInfoTokenServices and configuration classes.

**Comment by dsyer** [comment]
That won't work in quite that form because `UserInfoTokenServices` is part of Spring Boot now (which knows nothing about discovery).

**Comment by huningd** [comment]
Didn't saw that UserInfoTokenServices is from spring-boot-autoconfigure. Never develop in a text editor, sorry. So you mean you would enhance spring-cloud-security. Does that mean you would provide alternative configurations, exclude original configurations from spring-boot-autoconfigure and provide some alternative implementations. Do you have some recommendation how we could start to solve this?

**Comment by huningd** [comment]
We solved it now with the UserInfoRestTemplateCustomizer. It workes great vor us:
```java
    @Override
    public void customize(OAuth2RestTemplate template) {
        template.setRequestFactory(ribbonClientHttpRequestFactory);
    }
```

**Comment by kakawait** [comment]
@huningd good catch. However that is not enough to also support `security.oauth2.client.accessTokenUri`

You can do that thing (**ATTENTION not heavily tested and only tested with authorization-code mode, copy at your own risk**)

```
@Bean
UserInfoRestTemplateCustomizer userInfoRestTemplateCustomizer(SpringClientFactory springClientFactory) {
    return template -> {
        AccessTokenProviderChain accessTokenProviderChain = Stream
                .of(new AuthorizationCodeAccessTokenProvider(), new ImplicitAccessTokenProvider(),
                        new ResourceOwnerPasswordAccessTokenProvider(), new ClientCredentialsAccessTokenProvider())
                .peek(tp -> tp.setRequestFactory(new RibbonClientHttpRequestFactory(springClientFactory)))
                .collect(Collectors.collectingAndThen(Collectors.toList(), AccessTokenProviderChain::new));
        template.setAccessTokenProvider(accessTokenProviderChain);
    };
}
```

With that `Bean` following configuration is working

```
security:
  oauth2:
    client:
      accessTokenUri: http://uaa-service/oauth/token
```

where `uaa-service` is _service name_ (is not a resolvable hostname)

It can be a partial response for #94 we just need a trick for `userAuthorizationUri` (currently possible as explained on _POC_)
