### ISSUE TITLE
Support for Google oauth, `bearer` header is only in small letters.

### ISSUE THREAD

**Issue by patrykpacewicz** [spring-cloud/spring-cloud-security#63]
Hi,
I try to connect spring cloud security and google oauth. Spring security works nice because it allows me to use OAuth authentication by configuration only, but Google do not support the Spring way of sending a header `bearer` in small letters.

In such a case is there a possibility to connect :
* spring-cloud-security
* spring-security-oauth2
* @EnableOAuth2Sso
* `Bearer` with a capital letter  ?

Below is prepared example where I was able to get most parts connected.
The remaining part to get a fully functional outcome is a 'Bearer' with a capital letter

```groovy
    compile 'org.springframework.boot:spring-boot-starter-web:1.2.3.RELEASE'
    compile 'org.springframework.boot:spring-boot-starter-security:1.2.3.RELEASE'
    compile 'org.springframework.cloud:spring-cloud-security:1.0.1.RELEASE'
    compile 'org.springframework.security.oauth:spring-security-oauth2:2.0.7.RELEASE'
```

```groovy
@SpringBootApplication
@EnableOAuth2Sso
@Controller
class Application {
    static void main(String... args) {
        SpringApplication.run(Application, args);
    }

    @RequestMapping('/')
    @ResponseBody
    String home() {
        'Hello World'
    }
}
```

```yaml
spring:
  oauth2:
    client:
      clientId: XXXXXXXXXXXXXXXXXXX
      clientSecret: YYYYYYYYYYYYYYYYYY
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: query
      scope:
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
      preferTokenInfo: false
```

So how do you feel about the possibility of setting up a `bearer` header by configuration (eg via file)?
It seems to me that this type of change would open the spring-cloud-security for other tools like Google oauth
