### ISSUE TITLE
Question: Is there a way to secure endpoints with HTTP method type in configuration?

### ISSUE THREAD

**Issue by tjg184** [spring-cloud/spring-cloud-security#69]
Currently, below is what we have in our application.yml.  We need the ability to support securing paths by HTTP method.  It doesn't appear there is a way to do this without programmatically interacting with the org.springframework.security.config.annotation.web.builders.HttpSecurity object.  

```
sso:
    home:
        secure: false
        path: /index.html, /, /login, /user, /webjars/**
```

It would be convenient to be able to specify the HTTP method similar to the way you can specify paths.  We are currently developing a REST API where we need the ability to lock down different HTTP methods for the same URL.  Below is a proposed YAML configuration that would handle this and still be backwards compatible.  This would allow multiple paths to be specified along with multiple HTTP methods for that given path.  In the example below, "/api/customers" and "/api/products" would be available using the HTTP GET or POST.  In addition, this pattern could be extended for adding roles to a given URL.   

If there's an alternative way of doing this, I would like to hear that too.  I started to create a pull request, but wanted to confirm on the approach and make sure it doesn't already exist in some other way.    

```
sso:
    home:
        secure: false
        path: /index.html, /, /login, /user, /webjars/**
        paths:
            -
                path: /api/customers/**, /api/products/**
                method: GET,POST
                secure: false
```
