### ISSUE TITLE
[Question] LoadBalanced user-info-uri

### ISSUE THREAD

**Issue by marcosbarbero** [spring-cloud/spring-cloud-security#80]
Hi, I'm giving a try on Brixton.M1 and just get stuck on SSO.
At Angel.SR3 version I was able to get User info using loadbalancer with the following configuration:
```
spring:
  oauth2.resource:
    userInfoUri: http://security/user
    loadBalanced: true
``` 
In the Brixton.M1 I've tried the following:
```
security.oauth2.resource:
  user-info-uri: http://security/user
```
Looking at ResourceServerProperties class I didn't found the loadBalanced property, will it no longer be available, or am I missing something?
