### ISSUE TITLE
Authorization server behind Zuul

### ISSUE THREAD

**Issue by kakawait** [spring-cloud/spring-cloud-security#94]
I would be able to set my _AuthorizationServer_ behind _Zuul_ for multiple purposes (see below).

It's actually possible without changes POC https://github.com/kakawait/uaa-behind-zuul-sample but some tricks to do.
#### Enjoy _Zuul_/_Ribbon_ load balancing for HA _AuthorizationServer_

_AuthorizationServer_ for fully authenticated app is kind of `SPOF`, so it's important to replicate instances for HA. Instead of using it own load balancing why not using _Zuul_ like following architecture

![uaa behind zuul](https://cloud.githubusercontent.com/assets/275609/14349595/60ea6876-fcc4-11e5-8d82-48a9fe8a6d0d.png)
#### Do not expose _AuthorizationServer_ on web

I would _Zuul_ to be the only entry point of my application like previous architecture
#### Portable configuration

Related to https://github.com/spring-projects/spring-security-oauth/issues/671

Idea is to avoid any absolute URLs on following (at least) properties:
- `security.oauth2.client.accessTokenUri`
- `security.oauth2.client.userAuthorizationUri`

_Using path for `security.oauth2.client.userAuthorizationUri`?_
_Using service-registry for `security.oauth2.client.accessTokenUri`?_

Thus 

```
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/token
```

should becomes

```
security:
  oauth2:
    client:
      accessTokenUri: http://uaa-service/uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/token

zuul:
  routes:
    uaa-service:
      sensitiveHeaders:
      path: /uaa/**
```
